name: flexusrp_test_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.9+10
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  
  flutter:
    sdk: flutter

  ## ***** APP DEPENDENCIES ***** ##


  ## ***** FRAMEWORK DEPENDENCIES ***** ##  

  #Dev
  flutter_riverpod: ^2.1.3
  riverpod_annotation: ^1.1.1
  go_router: ^6.0.1
  easy_localization: ^3.0.1
  logger: ^1.1.0
  easy_logger: ^0.0.2
  lifecycle: ^0.6.0
  shared_preferences: ^2.0.17
  device_preview: ^1.1.0

  #UI
  flex_color_scheme: ^6.1.2
  sizer: ^2.0.15
  font_awesome_flutter: ^10.3.0
  google_fonts: ^4.0.1
  
  #Screen Spcific
  introduction_screen: ^3.1.4
  loading_overlay: ^0.3.0
  flutter_form_builder: ^7.7.0
  form_builder_validators: ^8.4.0
  package_info_plus: ^3.0.2
  flutter_animate: ^3.0.0

  #Image Editing
  image_picker: ^0.8.6+1
  image_cropper: ^3.0.1
  cached_network_image: ^3.2.3

  #API
  dio: ^4.0.6
  retrofit: ^3.3.1

  #PocketBase
  pocketbase: ^0.7.1+1

  #Extension Firebase

  #Firebase Core
  firebase_core: ^2.4.1

  #Firebase Auth
  firebase_auth: ^4.2.5
  crypto: ^3.0.2
  google_sign_in: ^5.4.4
  flutter_facebook_auth: ^5.0.7
  sign_in_with_apple: ^4.3.0
  cloud_firestore: ^4.3.1
  firebase_storage: ^11.0.10
  
  #Firebase Analytics
  firebase_analytics: ^10.1.0

  #Firebase Others
  firebase_crashlytics: ^3.0.11
  firebase_remote_config: ^3.0.9
  firebase_performance: ^0.9.0+10

  #Firebase testing
  firebase_core_platform_interface: ^4.5.2

  #Dialogs
  awesome_dialog: ^3.0.2


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  build_runner: any
  build_verify: any
  source_gen: any

  #API
  retrofit_generator: any

  #Futter Gen
  flutter_gen_runner: any

  #Riverpod Get
  riverpod_generator:

  #Validator
  dependency_validator: ^3.0.0
  

flutter_gen:
  output: lib/base/generated/assets

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/app/
    - assets/images/intro/  
    - assets/translations/
  fonts:
    - family: Poppins   
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
